services:
  rabbitmq-javamail:
    image: rabbitmq:3.13-management
    hostname: rabbitmq-javamail
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_JAVAMAIL_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_JAVAMAIL_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq-twilio:
    image: rabbitmq:3.13-management
    hostname: rabbitmq-twilio
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_TWILIO_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_TWILIO_PASSWORD}
    ports:
      - "5673:5672"
      - "15673:15672"
