version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-estoque
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-produtos-app
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq-javamail:
        condition: service_started
      rabbitmq-twilio:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&useUnicode=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
      app.rabbitmq.primary.host: rabbitmq-javamail
      app.rabbitmq.secondary.host: rabbitmq-twilio
      app.rabbitmq.secondary.port: 5672
    ports:
      - "8080:8080"
    networks:
      - app-network

  app-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-produtos-app-2
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq-javamail:
        condition: service_started
      rabbitmq-twilio:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&useUnicode=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
      app.rabbitmq.primary.host: rabbitmq-javamail
      app.rabbitmq.secondary.host: rabbitmq-twilio
      app.rabbitmq.secondary.port: 5672
    ports:
      - "8081:8080"
    networks:
      - app-network    

  app-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-produtos-app-3
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq-javamail:
        condition: service_started
      rabbitmq-twilio:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&useUnicode=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
      app.rabbitmq.primary.host: rabbitmq-javamail
      app.rabbitmq.secondary.host: rabbitmq-twilio
      app.rabbitmq.secondary.port: 5672
    ports:
      - "8082:8080"
    networks:
      - app-network

  rabbitmq-javamail:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-javamail
    hostname: rabbitmq-javamail
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_JAVAMAIL_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_JAVAMAIL_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  rabbitmq-twilio:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-twilio
    hostname: rabbitmq-twilio
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_TWILIO_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_TWILIO_PASSWORD}
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - app-network

  rabbitmq-images:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-images
    hostname: rabbitmq-images
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_IMAGES_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_IMAGES_PASSWORD}
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: