version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-estoque
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./estoque-de-produtos-crud/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - app-network

  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-produtos-app
    depends_on:
      - mysql
      - rabbitmq-javamail
      - rabbitmq-twilio 
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      app.rabbitmq.primary.host: rabbitmq-javamail
      app.rabbitmq.secondary.host: rabbitmq-twilio
      app.rabbitmq.secondary.port: 5672
    ports:
      - "8080:8080"
    networks:
      - app-network

  app-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-produtos-app-2
    depends_on:
      - mysql
      - rabbitmq-javamail
      - rabbitmq-twilio 
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      app.rabbitmq.primary.host: rabbitmq-javamail
      app.rabbitmq.secondary.host: rabbitmq-twilio
      app.rabbitmq.secondary.port: 5672
    ports:
      - "8081:8080"
    networks:
      - app-network    

  app-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-produtos-app-3
    depends_on:
      - mysql
      - rabbitmq-javamail
      - rabbitmq-twilio 
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      app.rabbitmq.primary.host: rabbitmq-javamail
      app.rabbitmq.secondary.host: rabbitmq-twilio
      app.rabbitmq.secondary.port: 5672
    ports:
      - "8082:8080"
    networks:
      - app-network

  rabbitmq-javamail:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-javamail
    hostname: rabbitmq-javamail
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_JAVAMAIL_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_JAVAMAIL_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  rabbitmq-twilio:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-twilio
    hostname: rabbitmq-twilio
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_TWILIO_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_TWILIO_PASSWORD}
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
